'use client'
import { useAppDispatch, useAppSelector } from "@/store";
import { addOne, initState, substractOne } from "@/store/counter/counterSlice";
import { useEffect, useState } from "react";

interface Props {
  value?: number// Generated by https://quicktype.io

  
}
interface CounterResponse {
 count: number;
 method:string;
}
const getCount = async ():Promise<CounterResponse> =>{
 const data = await fetch('/api/counter').then((res)=>res.json())
 return data
}
export function CounterCart({ value = 0 }: Props) {
  const dispatch = useAppDispatch()
  const count = useAppSelector(state => state.counter.count)

  useEffect(() => {
    getCount().then(({count}) =>{

      dispatch(initState(count))
    })
  }, [dispatch])


  return (
    <>
      <span className="text-9xl">{count}</span>

      <div className="flex">
        <button className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2" onClick={(e) =>  dispatch(addOne())}> +1</button>
        <button className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2" onClick={(e) => dispatch(substractOne())} >-1</button>
      </div> </>
  );
}